#development
server.port=8080
logging.level.org.springframework=debug

# @ value annotation
mykeys.profilepath=/varum/com/profilePhoto

#
varun.config.name=varun
varun.config.password=Varun5041@
varun.config.email=varunsoni21102005@gmail.com
varun.config.emailExpTime=5:30am